

fun main(args: Array<String>) {
  try {

  } catch (e: Exception) {
    println("EXCEPTION: ${e.message}")
  }
}